redditclone/accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.loginview, name='loginview'),
    url(r'^logout/', views.logoutview, name='logoutview'),
]

redditclone/posts/urls.py
from django.conf.urls import url
from posts import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
    url(r'^user/(?P<pk>[0-9]+)', views.user_post, name='user_post'),
    # url(r'^posts/(?P<pk>[0-9]+)', views.deleteview, name='deleteview'),
]

redditclone/redditclone/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),

]

redditclone/accounts/models.py
from django.db import models

# Create your models here.

redditclone/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.TextField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    votes_total = models.IntegerField(default=1)

    def __str__(self):
        return self.title

    def pub_date_new(self):
        return self.pub_date.strftime("%b %e %Y")

redditclone/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['pwd1'] == request.POST['pwd2']:
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error_key1':'User Already Exists. Choose Another Name'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['pwd1'])
                # login(request,user)
                # return render(request, 'accounts/login.html')
                return redirect('accounts:loginview')
        else:
            return render(request, 'accounts/signup.html', {'error_key2':'Passwords Did Not Match'})
    else:
        return render(request,'accounts/signup.html')

def loginview(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'],password=request.POST['pwd1'])

        if user is not None:
            login(request,user)

            if 'next' in request.POST:
                return redirect(request.POST['next'])

            return redirect('home')
        else:
            return render(request, 'accounts/login.html',{'error_key':'Username and Password Didn\'t Match'})

    else:
        return render(request, 'accounts/login.html')

@login_required
def logoutview(request):
    logout(request)
    return redirect('home')

redditclone/posts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.views.generic import DeleteView
from django.utils import timezone
from posts.models import Post
from django.contrib.auth.models import User

# Create your views here.
@login_required
def create(request):
    '''title and url coming from create.html textfield'''
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']

            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = "http://" + request.POST['url']

            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('home')
        else:
            return render(request, 'posts/create.html', {'error':'ERROR. Fill in all the Field'})
    else:
        return render(request,'posts/create.html')

def home(request):
    posts = Post.objects.order_by('-votes_total')
    return render(request, 'posts/home.html',{'posts':posts})

def upvote(request,pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect('home')

def downvote(request,pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
        return redirect('home')

def user_post(request,pk):
    post = Post.objects.filter(author__id=pk).order_by('-votes_total')
    author = User.objects.get(pk=pk)
    return render(request, 'posts/user_post.html', {'post':post, 'author':author})

def deleteview(request,pk):
    post = Post.objects.get(pk=pk)
    post_pk = post.pk
    post.delete()
    post.save()
    return redirect('home')

# class PostDeleteView(LoginRequiredMixin,DeleteView):
#     model = Post
#     # after deleting any post, it will go to success_url
#     success_url = reverse_lazy('home')

redditclone/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block body_block %}
  <div class="jumbotron">

    <h1>Please Login</h1>
    <form action="" method="POST">
      {% csrf_token %}

      {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
      {% endif %}

      <label for="uname">User Name:</label>
      <input type="text" id="uname" name="username" placeholder="Enter User Name"><br/><br/>

      <label for="pass">Password:</label>
      <input type="password" id="pass" name="pwd1" placeholder="Enter Password"><br/><br/>
      <span class='help-block'>
        {% if error_key %}
          <h2>{{error_key}}</h2>
        {% endif %}
      </span>

      <button type="submit" class="btn btn-primary" value="Signup">Login</button>

    </form>

  </div>

{% endblock %}

redditclone/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block body_block %}
  <div class="jumbotron">

    <h1>Register Here</h1>

      {% if error_key1 %}
        <h2>{{error_key1}}</h2>
      {% endif %}

      {% if error_key2 %}
        <h2>{{error_key2}}</h2>
      {% endif %}

    <form action="" method="POST">
      {% csrf_token %}
      <label for="username">User Name:</label>
      <input type="text" name="username" placeholder="Enter UserName"><br/><br/>

      <label for="pwd1">Password:</label>
      <input type="password" name="pwd1" placeholder="Enter Password"><br/><br/>

      <label for="pwd2">Password Again:</label>
      <input type="password" name="pwd2" placeholder="Confirm Password"><br/><br/>

      {% if error_key %}
        <h2>{{error_key}}</h2>
      {% endif %}

      <button type="submit" class="btn btn-primary" value="Signup">Sign Up</button>

    </form>

  </div>

{% endblock %}

redditclone/posts/templates/posts/create.html
{% extends 'base.html' %}

{% block body_block %}
  <div class="jumbotron">
    <h3>Create New Post</h3>
    <form action="{% url 'posts:create' %}" method="POST">
      {% csrf_token %}
      <div class="form-group form-group-md">
        <label for="title">Title</label>
        <input class="form-control" id="title" name="title" type="text">

        <label for="url">URL</label>
        <input class="form-control" id="url" name="url" type="text">
      </div>
      <button type="submit" class="btn btn-primary" value="Signup">Post</button>
      {% if error %}
        {{error}}
      {%  endif %}


    </form>

  </div>
{% endblock %}

redditclone/posts/templates/posts/home.html
{% extends "base.html" %}

{% block body_block %}

  {% for post in posts %}

    <table>
      <tr>
        <td style="padding-right:20px"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top"></span></a><br/>{{post.votes_total}}<br/><a href="" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom"></span></a></td>

        <td><h4><a href="{{post.url}}">{{post.title}}</a></h4><span class="glyphicon glyphicon-time">{{post.pub_date_new}}</span> Posted by: <a href="{% url 'posts:user_post' post.author.id %}"><strong>{{post.author.username}}</strong></a></td>

        {# <br/><a href="#"><span class="glyphicon glyphicon-pencil"></span></a> #}
        {# &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'posts:deleteview' post.id %}"><span class="glyphicon glyphicon-trash"></span></a> #}
      </tr>
    </table>
    <p>------------------------------------------------------------------------------------------------------------------------</p>

    <form id="upvote{{ post.id }}" action="{% url 'posts:upvote' post.id %}" method="POST">
      {% csrf_token %}
      <input type="hidden">
    </form>
    <form id="downvote{{ post.id }}" action="{% url 'posts:downvote' post.id %}" method="POST">
      {% csrf_token %}
      <input type="hidden">
    </form>
  {% endfor %}

{% endblock %}

redditclone/posts/templates/posts/user_post.html
{% extends "base.html" %}

{% block body_block %}
  <h3>All Posts by {{author.username}}</h3>

  {% for post in post %}

    <table>
      <tr>
        <td style="padding-right:20px"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top"></span></a><br/>{{post.votes_total}}<br/><a href="" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom"></span></a></td>

        <td><h4><a href="{{post.url}}">{{post.title}}</a></h4><span class="glyphicon glyphicon-time">{{post.pub_date_new}}</span> Posted by: <a href="{% url 'posts:user_post' post.author.id %}"><strong>{{post.author.username}}</strong></a></td>
      </tr>
    </table>
    <p>------------------------------------------------------------------------------------------------------------------------</p>

    <form id="upvote{{ post.id }}" action="{% url 'posts:upvote' post.id %}" method="POST">
      {% csrf_token %}
      <input type="hidden">
    </form>
    <form id="downvote{{ post.id }}" action="{% url 'posts:downvote' post.id %}" method="POST">
      {% csrf_token %}
      <input type="hidden">
    </form>
  {% endfor %}
{% endblock %}

redditclone/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Reddit Clone</title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav1" aria-expanded="false">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Reddit Clone</a>
        </div>
        <div class="collapse navbar-collapse" id="nav1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'posts:create' %}">New Post</a></li>
            <li><a href="#">Contact</a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a href="#">Welcome {{user.username}}</a></li>
              <li><a href="{% url 'accounts:logoutview' %}">Logout</a>
              </li>
            {% else %}
              <li><a href="{% url 'accounts:signup' %}">Register</a>
              </li>
              <li><a href="{% url 'accounts:loginview' %}">Login</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>